import type { Metadata } from 'next'
import GlobalLayout from '@/components/global-layout'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return <GlobalLayout>{children}</GlobalLayout>
}
